### ISSUE TITLE
Dock icon has (incorrect) "muted" badge for video ads, too

### ISSUE THREAD

**Issue by Fofer** [w0lfschild/spotifyPlus#1]
I installed this and it appears to be working great. I love the dynamic dock icon!

I did notice it mute the first audio ad (for Burger King.) Sweet. But that was followed by two video ads (one for Samsung Galaxy Note and another for Spotify Premium.) And even though the dock icon still had the "muted" badge on it, the sound from those video ads played. Are video ads supposed to be muted too? If not, is this something that may be improved in the future?

**Comment by w0lfschild** [comment]
I think it would be possible to mute OSX when video ads play but the video ads are not controlled by the spotify volume so I'm not sure of another solution.

**Comment by w0lfschild** [comment]
Actually by editing the hosts file you can block all Ads including banners and seems to block video and audio ads as well.

0.3 has the ability to make that edit.

Playback > spotifyAB > Advertisements > Block banner Ads

**Comment by Fofer** [comment]
That is supremely awesome.  Thank you!
