### ISSUE TITLE
Add an option to disable the badge

### ISSUE THREAD

**Issue by matthewdias** [w0lfschild/spotifyPlus#2]

**Comment by w0lfschild** [comment]
Done https://github.com/w0lfschild/spotifyPlus/commit/c677c2f146b0b5a235c98409e2dd0e402993e8c0

**Comment by w0lfschild** [comment]
Compiled version of 0.5.3 is available in mySIMBL or a direct [download](https://github.com/w0lfschild/myRepo/raw/master/mytweaks/bundles/spotifyPlus_0.5.3.zip).
