### ISSUE TITLE
spotifyPlus is not working with the new version of Spotify app

### ISSUE THREAD

**Issue by rafalenden** [w0lfschild/spotifyPlus#3]
Just installed spotifyPlus plugin but looks like it doesn't work.

The icon doesn't change to the cover, also the menu item "Spotify+" doesn't appear in the Spotify app.

OS: Sierra 10.12.2
MySIMBL: 0.4.3
spotifyPlus: 0.6.0

**Comment by w0lfschild** [comment]
Make sure that mySIMBL is actually working and that you have restarted Spotify since you installed the tweak. 

The tweak is working on the latest version of Spotify 1.0.45.186.g3b5036d6.

**Comment by rafalenden** [comment]
The plugin works only if I press "Load into all running applications" and if I run Spotify again I need to press the button again to make it work. Is that a known issue?

Related issue https://github.com/w0lfschild/mySIMBL/issues/13

**Comment by rafalenden** [comment]
Related issue https://github.com/w0lfschild/mySIMBL/issues/13

**Comment by Fofer** [comment]
For what it's worth, I have the same versions of softwares installed and Spotify+ is working for me, without any need to press the  "Load into all running applications" button.
