### ISSUE TITLE
Black Bar Where Ads Used to be

### ISSUE THREAD

**Issue by Osirus** [w0lfschild/spotifyPlus#4]
Hi W0lfschild,
First, I want to say thank you for making, and maintaining this!  I was wondering if this bar is supposed to be here: https://i.imgur.com/XNKhAco.png and if there is a way to remove it? 

Thanks!
Edit: This is the black bar (near the bottom):
<img width="1136" alt="screenshot 2017-10-09 22 51 57" src="https://user-images.githubusercontent.com/27123848/31367387-182039c6-ad45-11e7-9fae-f25b12c6b8fc.png">

Please let me know if there is any other information you would like from me to help with this issue :)

**Comment by w0lfschild** [comment]
Yeah I'm not sure how I would remove that. The entire window is a webview and I don't really know how to work with those.

**Comment by Machaan** [comment]
@w0lfschild Hey I'm Osirus (just remembered my old Github account)... I just wanted to let you know that it appears to be solved now :)
![image](https://user-images.githubusercontent.com/26804396/37261282-ae2de612-2571-11e8-9d31-209dfea671d5.png)

**Comment by w0lfschild** [comment]
Yeah which is nice because it was something they changed in the app, not me 👍
