### ISSUE TITLE
Icon art style does not work

### ISSUE THREAD

**Issue by tanliktjunbryan** [w0lfschild/spotifyPlus#5]
When icon art style is changed, Spotify crashes and restarts and icon art style remains the same, otherwise everything else is great.

**Comment by w0lfschild** [comment]
Is there a crash log?

**Comment by tanliktjunbryan** [comment]
No, sorry there isnt

**Comment by JMY1000** [comment]
This issue seems to only come up for me when I try to change the album art to either of the two circular styles and "Show icon art" is off. Turning it on before trying to change the art style seems to fix it.

**Comment by w0lfschild** [comment]
Does this still happen with the latest version? I could probably add some checks to at least stop it from crashing but I can't reproduce this personally.

**Comment by JMY1000** [comment]
Seems like it.

**Comment by carsuki** [comment]
This happens for me as well. When changing the icon to one of the circle styles, it crashes spotify and the icon doesn't change. It does this even if "Show icon art" is off.
