### ISSUE TITLE
Not injecting in 1.0.87.491.ge2a121fc and above

### ISSUE THREAD

**Issue by sidpagariya** [w0lfschild/spotifyPlus#8]
The spotify+ menu doesn't seem to show up in version `1.0.87.491.ge2a121fc` of Spotify now...

**Comment by sidpagariya** [comment]
It now works in `1.0.86.337.ga8d5cef9`... Yes, I did downgrade for now, but @w0lfschild do you mind checking for `1.0.87.491.ge2a121fc`? Thanks!

**Comment by Machaan** [comment]
I'm having the same issue as @sidpagariya on both of the two newest updates: 1.0.87.491.ge2a121fc and 1.0.88.353.g15c26ea1. It works great again on 1.0.86.337 though after downgrading just like sidpagariya stated.  I can't seem to find the change logs.

**Comment by w0lfschild** [comment]
* What version of macOS are you on?
* Do you have SIP off?

**Comment by sidpagariya** [comment]
- I'm on macOS 10.14 (18A371a), Developer Beta 8
- I do indeed have SIP off and I upgraded Spotify, after which it stopped working...

**Comment by Fofer** [comment]
I'm on MacOS 10.13.6.  Spotfiy+ was working for me fine, until Spotify
updated to 1.0.87.491 just now, and now Spotify+ isn't working for me
anymore.

I'm a paid Spotify user, but appreciate the Dock badging feature that
Spotify+ had been granting me.

**Comment by w0lfschild** [comment]
Interesting it's working fine for me on the latest version `1.0.88.353.g15c26ea1` on `macOS 10.14 (18A371a)`.

**Comment by w0lfschild** [comment]
What version of spotify+ are you all using? I realized I had version 0.6.0 on my personal mySIMBL repo but 0.6.3 is the most current version.

**Comment by Machaan** [comment]
I'm using 0.6.0-- I hadn't realized there was an update for it. I'll try it out right now and report back as soon as I can

**Comment by Machaan** [comment]
Yeah, it still isn't working for me after I updated to 0.6.3 via mySIMBL's update section and I updated Spotify to 1.0.88.353.g15c26ea1. Maybe I need to delete it and redownload spotifyPlus manually or restart my Macbook Pro for it to take effect?

**Comment by Machaan** [comment]
I was able to get it to work-- What I did was the following: I uninstalled/ deleted Spotify and make sure no application leftovers were still there. Then I removed spotifyPlus.bundle from mySIMBL and closed out of mySIMBL. Next, I downloaded the latest Spotify installer and installed Spotify. I quit Spotify, and then opened mySIMBL. From the Discover tab, I installed spotifyPlus, then reopened Spotify, and it worked! For some reason, whenever I would update from 0.6.0 to 0.6.3 within mySIMBL without first removing/deleting the 0.6.0 bundle, it wouldn't work in Spotify.

**Comment by sidpagariya** [comment]
Woah @w0lfschild weird that mySIMBL didn't show updates for the 0.6.3 package and even after reinstalling from scratch, it still installed 0.6.0 instead of 0.6.3...

Update: it finally shows up after multiple tries of opening and closing with the occasional refresh button hit

**Comment by sidpagariya** [comment]
@Shapsuo I'll give that a try now!

**Comment by sidpagariya** [comment]
Lol Spotify doesn't even show me a 1.0.88 version for updates haha, even after disabling blocks in /etc/hosts 😆

**Comment by Machaan** [comment]
@sidpagariya I uninstalled Spotify using AppDelete (making sure to not remove any files I still needed).  I just downloaded the 1.0.88 .dmg file from the Spotify website and installed it from there.

**Comment by sidpagariya** [comment]
Thanks @Shapsuo  I did try that once before the spotifyPlus stopped working but I'll try it again lol

**Comment by Fofer** [comment]
I uninstalled Spotify and SpotifyPlus completely.  I downloaded and
installed Spotify, and am now running 1.0.88.353.g15c26ea1.  I then also
installed SpotifyPlus 0.6.3.  I rebooted my Mac and launched Spotify,
logged in and customized my settings.

However, I'm still not seeing the SpotifyPlus menu or getting any of its
features.  I am a paid Spotify user, if that matters here.  I am running
the most current macOS official release, 10.13.6.  Is there anything else I
should be trying?

**Comment by sidpagariya** [comment]
I did do the same things as @Shapsuo, and still no luck on 1.0.88.353.g15c26ea1 with multiple application and plugin uninstallations and reinstallations...

**Comment by Machaan** [comment]
Hey @sidpagariya @w0lfschild  -- I restarted my computer and now it stopped working, and I can't seem to get it to work again. =/ Sorry... I thought I had a method that worked for some reason >.<

**Comment by Machaan** [comment]
I've spent quite a bit of time testing out different methods to see if I could get it to work again with 0.6.3 for 1.0.88.353.g15c26ea1, but to no avail :( mySIMBL version is 0.7.1, and this is my System Info tab:


![1](https://user-images.githubusercontent.com/26804396/44541091-ea5d5f00-a6d6-11e8-8e2c-44eb5fa71cb2.png)




Here is a screenshot of my Manage Tab with spotifyPlus showing:


<img width="730" alt="screenshot 2018-08-23 13 11" src="https://user-images.githubusercontent.com/26804396/44540791-0c0a1680-a6d6-11e8-9323-23f64a29202f.png">

I'm on High Sierra 10.13.6 (17G65).

Please let me know if you need any other information to help solve this. Thanks!

**Comment by w0lfschild** [comment]
@Machaan Looks like you have System Integrity Protection on in your photo. 

Assuming you're on 10.14 (more injection security) maybe that's the issue?

**Comment by Machaan** [comment]
@w0lfschild Ahh thanks! I didn't notice that it turned back on. But that isn't it sadly... 
<img width="271" alt="screenshot 2018-08-23 17 58 51" src="https://user-images.githubusercontent.com/26804396/44554247-3a9be780-a6fe-11e8-8ff6-54298ca03b71.png">


I'm on 10.13.6 (17G65) -- High Sierra (Not Mojave). I tried doing a clean install of spotifyPlus after removing it, but that didn't make a difference with Spotify 1.0.88.353.g15c26ea1.

**Comment by sidpagariya** [comment]
I hope this is what we need to expect for the requirements of mySIMBL:
<img width="249" alt="screen shot 2018-08-23 at 6 04 02 pm" src="https://user-images.githubusercontent.com/10685754/44554449-0543c980-a6ff-11e8-8a65-6779f728be18.png">

I have been blocking updates for Spotify and downgraded to 1.0.80 using the DMG on Spotify's website... and spotifyPlus is temporarily working...

**Comment by Fofer** [comment]
How exactly do you block updates for Spotify?

**Comment by sidpagariya** [comment]
I chmod the app so it can't be replaced even by the update mechanism...

**Comment by w0lfschild** [comment]
Interesting maybe you're in some A/B testing by spotify? Do other plugins load for you all?

**Comment by Machaan** [comment]
Nothing is working with the latest version of Spotify for me. Not even F-Script shows up in the menubar:

Latest Version:

<img width="696" alt="latest" src="https://user-images.githubusercontent.com/26804396/44558269-244b5700-a711-11e8-8e5a-8413d3b8ff4a.png">


Older Version:

<img width="721" alt="old" src="https://user-images.githubusercontent.com/26804396/44558277-33320980-a711-11e8-8a47-6c874c0f768d.png">

**Comment by Machaan** [comment]
@sidpagariya What were the exact chmod commands that you used? I used an old script I had saved from before I discovered @w0lfschild 's spotifyPlus/mySIMBL and denied a couple of connections with Little Snitch:

``` sh
#This script prevents Spotify from Autoupdating on OS X (tested on Yosemite)
#This script must be run as root:
#sudo sh donotupdatespotify.sh
FILE="/tmp/out.$$"
if [ "$(id -u)" != "0" ]; then
echo "This script must be run as root"
echo "-------------------------------------------"
echo "This is what you should type into terminal:"
echo "sudo sh Page on donotupdatespotify.sh"
exit 1
fi

filepath1="/Users/$SUDO_USER/Library/Application
Support/Spotify/Spotify_new.archive"

filepath2="/Users/$SUDO_USER/Library/Application
Support/Spotify/Spotify_new.archive.sig"
-f "$filepath1" && rm -f "$filepath1"
-f "$filepath2" && rm -f "$filepath2"
touch "$filepath1"
touch "$filepath2"
chflags uchg "$filepath1" # Lock file in which the downloaded update
is stored, thus preventing an update
chflags uchg "$filepath2"
echo "---------------------------------------"
echo "| Spotify will no longer be updated |"
echo "---------------------------------------"
```

Was it the same thing as this: [https://gist.github.com/aleksandrs-ledovskis/0b149b996c7a1ebc16126c60a79433ec](https://gist.github.com/aleksandrs-ledovskis/0b149b996c7a1ebc16126c60a79433ec) ? Also, btw I noticed we are from the same state :)

**Comment by sidpagariya** [comment]
@Machaan basically that script but the update mechanism I thought was changed so I had to do stuff with locking (the `chflags` command with the `uchg` flag) the `/Applications/Spotify.app/` and `~/Library/Application\ Support/Spotify/PersistentCache/Update/` and I locked the files inside it...
The only annoying thing is that Spotify asks my password when I open it up lol, but it's all good haha

**Comment by anonymouz4** [comment]
Doesn't work for me either on 10.13.6 and newest Spotify

**Comment by anonymouz4** [comment]
**Found a temporary fix:**
Download Version 1.0.86 DMG: from [here](https://mac.filehorse.com/download-spotify/10715/) for example

Block this Address (I prefer using Vallum): **beta.spotify.map.fastly.net (151.101.120.246) - Port 443**

Open the Downloaded DMG and replace the existing Spotify with the Dowloaded.
It will still say new Verion available but won't be able to download

**Comment by dbolger** [comment]
> **Found a temporary fix:**
> Download Version 1.0.86 DMG: from [here](https://mac.filehorse.com/download-spotify/10715/) for example
> 
> Block this Address (I prefer using Vallum): **beta.spotify.map.fastly.net (151.101.120.246) - Port 443**
> 
> Open the Downloaded DMG and replace the existing Spotify with the Dowloaded.
> It will still say new Verion available but won't be able to download

This does indeed work.

I'm going to assume methods have changed and they differ from what is currently being used in the header. Probably need to dump new headers so we know what to change.

**Comment by Fofer** [comment]
It’s worthwhile to read Spotify’s new terms of service:

Spotify will soon ban accounts that use ad blockers
https://www.cultofmac.com/605788/spotify-ban-accounts-ad-blockers/

**Comment by anonymouz4** [comment]
@Fofer Trust me, there is always a way to bypass things like this

**Comment by w0lfschild** [comment]
I can get this to load with both SIP and AMFI off using [MacForge](https://github.com/w0lfschild/MacForge).

<img width="832" alt="Screen Shot 2019-08-09 at 11 41 08 PM" src="https://user-images.githubusercontent.com/1920148/62818675-3cbda880-baff-11e9-8c35-563151776a56.png">

macOS - `10.15`
Spotify  - `1.1.10.540.gfcf0430f`

Problem is that if you're using this for the complete ad block, that was just altering the hosts file which no longer works.

If you like this tweak for the custom icon or the auto muting of ads that will still work.
